/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_prog_1(char *host, char *argv[], int opera)
{
	CLIENT *clnt;
	float  *result_1;
	nums  suma_1_arg;
	float  *result_2;
	nums  resta_1_arg;
	float  *result_3;
	nums  multiplicacion_1_arg;
	float  *result_4;
	nums  division_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

switch(opera){
	case 1:
	suma_1_arg.n1 = atoi(argv[3]);
	suma_1_arg.n2 = atoi(argv[4]);
	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("La suma es %f\n",*result_1);
	}
	break;
	case 2:
	resta_1_arg.n1 = atoi(argv[3]);
	resta_1_arg.n2 = atoi(argv[4]);
	result_2 = resta_1(&resta_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("La resta es %f\n",*result_2);
	}
	break;
	case 3:
	multiplicacion_1_arg.n1 = atoi(argv[3]);
	multiplicacion_1_arg.n2 = atoi(argv[4]);
	result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("La multiplicacion es %f\n",*result_3);
	}
	break;
	case 4:
	division_1_arg.n1 = atoi(argv[3]);
	division_1_arg.n2 = atoi(argv[4]);
	result_4 = division_1(&division_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("La division es %f\n",*result_4);
	}
	break;
}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s \nserver_host, \noperation(1.suma,2.resta,3.multiplicacion,4.division)\nand two numbers\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int opera = atoi(argv[2]);
	calculadora_prog_1 (host,argv,opera);
exit (0);
}
