/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct nums {
	float n1;
	float n2;
};
typedef struct nums nums;

#define CALCULADORA_PROG 0x31111111
#define CALCULADORA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  float * suma_1(nums *, CLIENT *);
extern  float * suma_1_svc(nums *, struct svc_req *);
#define resta 2
extern  float * resta_1(nums *, CLIENT *);
extern  float * resta_1_svc(nums *, struct svc_req *);
#define multiplicacion 3
extern  float * multiplicacion_1(nums *, CLIENT *);
extern  float * multiplicacion_1_svc(nums *, struct svc_req *);
#define division 4
extern  float * division_1(nums *, CLIENT *);
extern  float * division_1_svc(nums *, struct svc_req *);
extern int calculadora_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  float * suma_1();
extern  float * suma_1_svc();
#define resta 2
extern  float * resta_1();
extern  float * resta_1_svc();
#define multiplicacion 3
extern  float * multiplicacion_1();
extern  float * multiplicacion_1_svc();
#define division 4
extern  float * division_1();
extern  float * division_1_svc();
extern int calculadora_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nums (XDR *, nums*);

#else /* K&R C */
extern bool_t xdr_nums ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
